apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  defaultBackend:
    service:
      name: {{ .Chart.Name }}
      port:
        number: {{ .Values.specs.ingress.port }}
  rules:
    - host: {{ .Values.specs.ingress.publicUrl }}
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: {{ .Chart.Name }}
                  port:
                    number: {{ .Values.specs.ingress.port }}