replicaCount: 1
image:
  repository: challenge12.azurecr.io/challenge-server

publicUrl: "challengedevops-server.duckdns.org"

specs:
  ingress:
    publicUrl: challengedevops-server.duckdns.org
    port: 8080
  service:
    name: http
    port: 8080
    protocol: TCP
    type: ClusterIP

env:
  CORS_ALLOWLIST: "http://challengedevops.duckdns.org/"